/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// KubeCopilotNotificationSpec defines the content of a one-way notification
// from the agent to the user session, typically triggered by background tasks.
type KubeCopilotNotificationSpec struct {
	// AgentRef is the name of the KubeCopilotAgent that produced this notification.
	// +required
	AgentRef string `json:"agentRef"`

	// SessionID is the conversation session this notification belongs to.
	// +required
	SessionID string `json:"sessionID"`

	// Message is the notification body (supports markdown).
	// +required
	Message string `json:"message"`

	// NotificationType categorises the notification: info, success, warning, error.
	// +kubebuilder:validation:Enum=info;success;warning;error
	// +kubebuilder:default="info"
	// +optional
	NotificationType string `json:"notificationType,omitempty"`

	// Title is an optional short summary shown in toasts.
	// +optional
	Title string `json:"title,omitempty"`

	// TaskRef is an optional reference to the background task that generated this notification.
	// +optional
	TaskRef string `json:"taskRef,omitempty"`
}

// KubeCopilotNotificationStatus defines the observed state of KubeCopilotNotification.
type KubeCopilotNotificationStatus struct {
	// CreatedAt is the timestamp when this notification was recorded.
	// +optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="AgentRef",type="string",JSONPath=".spec.agentRef"
// +kubebuilder:printcolumn:name="SessionID",type="string",JSONPath=".spec.sessionID"
// +kubebuilder:printcolumn:name="Type",type="string",JSONPath=".spec.notificationType"
// +kubebuilder:printcolumn:name="Title",type="string",JSONPath=".spec.title"

// KubeCopilotNotification is the Schema for the kubecopilotnotifications API.
// It represents a one-way message from the agent to the user session,
// typically generated by background tasks such as resource monitoring.
type KubeCopilotNotification struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   KubeCopilotNotificationSpec   `json:"spec"`
	Status KubeCopilotNotificationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KubeCopilotNotificationList contains a list of KubeCopilotNotification
type KubeCopilotNotificationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KubeCopilotNotification `json:"items"`
}

func init() {
	SchemeBuilder.Register(&KubeCopilotNotification{}, &KubeCopilotNotificationList{})
}
