apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-copilot-ui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-copilot-ui.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kube-copilot-ui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
