---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecopilot.io
  resources:
  - kubecopilotagents
  - kubecopilotcancels
  - kubecopilotchunks
  - kubecopilotmessages
  - kubecopilotnotifications
  - kubecopilotsends
  - kubecopilotsessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecopilot.io
  resources:
  - kubecopilotagents/finalizers
  - kubecopilotmessages/finalizers
  - kubecopilotsends/finalizers
  - kubecopilotsessions/finalizers
  verbs:
  - update
- apiGroups:
  - kubecopilot.io
  resources:
  - kubecopilotagents/status
  - kubecopilotcancels/status
  - kubecopilotchunks/status
  - kubecopilotmessages/status
  - kubecopilotnotifications/status
  - kubecopilotsends/status
  - kubecopilotsessions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubecopilot.io
  resources:
  - kubecopilotresponses
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
