## Append samples of your project ##
resources:
- agent_v1_kubecopilotagent.yaml
- agent_v1_kubecopilotmessage.yaml
- kubecopilot_v1_kubecopilotsend.yaml
- agent_v1_kubecopilotsession.yaml
- agent_v1_kubecopilotmodelconfig.yaml
- agent-md-configmap.yaml
- skills-configmap.yaml
- namespace.yaml
