apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kube-copilot-console-plugin.patcherName" . }}
  labels:
    {{- include "kube-copilot-console-plugin.labels" . | nindent 4 }}
rules:
  - apiGroups: ["operator.openshift.io"]
    resources: ["consoles"]
    verbs: ["get", "list", "patch"]
