{{- if .Values.plugin.patcherServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-copilot-console-plugin.patcherServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-copilot-console-plugin.labels" . | nindent 4 }}
  {{- with .Values.plugin.patcherServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
